version: '3.8'

services:
  backend:
    build: 
      context: .
      target: development
    container_name: resume-customizer-backend-dev
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    ports:
      - "9229:9229" # For debugging

  postgres:
    ports:
      - "5432:5432" # Expose on host for local dev tools

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - resume-customizer-network
